changed tar installation command

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,7 +41,16 @@ jobs:
         command: |
           if ! command -v tar &> /dev/null; then
             echo "Installing tar..."
-            yum install -y tar || apk add tar || apt-get update && apt-get install -y tar
+          if [ -f /etc/debian_version ]; then
+            apt-get update && apt-get install -y tar
+          elif [ -f /etc/alpine-release ]; then
+            apk add --no-cache tar
+          elif [ -f /etc/redhat-release ]; then
+            yum install -y tar
+          else
+          echo "Unsupported OS, tar installation failed!"
+            exit 1
+          fi
           fi
     - attach_workspace:
         at: ~/repo
